### PR TITLE
Restrict to Facebook's calendar URLs

### PR DESCRIPTION
**Pull request by mems**
Protect this script to be used as a web proxy
http://eventcal.flown.io/?calendar=http%3A%2F%2Fgoogle.com

### CODE REVIEW

**Comment by simonbengtsson** [comment]
Looks like a good idea! Updated the site with these changes now.

**Comment by simonbengtsson** [comment]
This tickled my curiosity somewhat... Are there any security risks as it were before? Or just that the service might be used for things it was not intended for?

**Comment by mems** [comment]
An open proxy could be used to abuse to remote servers (spamming, vandalism) or access to illegal content, but hidden behind your server.
https://en.wikipedia.org/wiki/Open_proxy#Disadvantages
https://www.internet2.edu/presentations/spring03/20030409-OpenProxy-StSauver.pdf#p=56
eventcal is not a HTTP proxy: only GET without header requests are allowed. It's still a risk.

**Comment by simonbengtsson** [comment]
Make sense! Thanks for the info.

**Pull request merged**
